{% set name = "vartriage" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools >=77
    - wheel
  run:
    - python >=3.10

test:
  imports:
    - vartriage
  commands:
    - vartriage --help

about:
  home: https://github.com/MOMA-AUH/vartriage
  summary: Perform second opinions on variant calls using evidence VCFs
  license: MIT
  license_file: LICENSE
